auth-server-url: http://mkyauth.jinxin.cloud:8080

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000

spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.1.1.91:3306/auth_server_dev?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    hikari:
      maximum-pool-size: 3
#    url: jdbc:mysql://127.0.0.1:33010/auth_server_dev?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://10.1.1.176:32706/uc_server_dev
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  redis:
    #数据库索引
    database: 1
    host: 10.1.1.91
#    host: 10.1.1.176
    port: 6379
    #    password: 12345
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000
  security:
    user:
      name: root
      password: root

security:
  oauth2:
    client:
      client-id: testclientid
      client-secret: 123456
      scope: read_userinfo
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      user-info-uri: ${auth-server-url}/user
      token-info-uri: ${auth-server-url}/oauth/check_token
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

seaboxdata:
  core:
    idgenerator:
      mode: snowflake
      datacenter: 1
      worker: 1
  auth:
    hostname:
    host: localhost
    url: http://${spring.application.name}

logging:
  level:
    com.seaboxdata.auth.server.dao: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8080
    non-secure-port-enabled: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

token:
  domain: jinxin.cloud

rocketmq:
  name-server: 10.1.1.176:9876
  producer:
    send-message-timeout: 3000
    group: auth_${spring.profiles.active}

cas:
  bj:
    ws:
      url: https://10.1.3.21:8087/portal/intlDataSynchronizedService?wsdl
    server:
      #cas验证路径
      prefix: https://10.1.3.21:17002/cas
#      prefix: http://118.126.103.216:17001/cas
      project: https://mkyauth.jinxin.cloud:32797
    #cas过滤器拦截路径
    intercept: /bj/cas/authDoLogin
    filter:
      #设置cas过滤器配置是否开启
      enabled: false
    sync:
      password: dfjx