auth-server-url: http://localhost:8080

spring:
  application:
    name: auth-frontier
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password: 12345
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000
    security:
      user:
        name: root
        password: root

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://r480.stan.cc:8762/eureka

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

seaboxdata:
  core:
    idgenerator:
      mode: snowflake
      datacenter: 1
      worker: 1
  auth:
    hostname: localhost:8080
    url: http://auth-server
  tag:
    hostname: localhost:9009

security:
  oauth2:
    client:
      client-id: testclientid
      client-secret: 123456
      scope: read_userinfo
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token

token:
  #  domain: auth.cbacb.com
  #  domain: auth.dev.ej.stan.cc
  domain: stan.cc
  access-token:
    expiration-time: 120 # 60 * 60 * 12 * 2
  #    expiration-time: 86400 # 60 * 60 * 12 * 2
  refresh-token:
    expiration-time: 2592000 # 60 * 60 * 12 * 2 * 30

logging:
  level:
    "org.springframework": info